Feature/9 agent shifting
openbase/planetsudo.engine pull request #34
Opened 2024-02-17 19:32 UTC by DivineThreepwood

### :scroll: Description

Changes proposed in this pull request:
* Finish implementation of shift feature.
* Improve game sounds. 
* Cleanup docs. 
* Rename `errect`Tower to `construct`Tower.

### :hammer: Breaking Changes

* Rename `errect`Tower to `construct`Tower.

### :white_check_mark: Checklist:
- [x] Extended the documentation

2024-02-18 08:30 UTC, tommy33790 requested changes
Both new sound files aren't published with the engine and therefore aren't available to the ai project.
As the files don't exist in `planetsudo\src\main\resources\sound\` the `AudioDataImpl` throws a `CouldNotPerformException` which isn't caught in `GameSound.init` resulting in the executed rule failing and killing the corresponding agent.

2024-02-18 13:59 UTC, DivineThreepwood commented
Actually I thought I fixed this. Ok, I will investigate again here.

2024-02-18 14:14 UTC, DivineThreepwood commented
Hmm, sorry I am not able to reproduce this issue. The GameManager handles if sound files are not available:

```
15:10:58.001 [GravityGangAgentThread] ERROR org.openbase.planetsudo.game.GameSound -- ═╦═⚀ Could not load Soundfile[sound/sirene.thaoeuth] of MothershipUnderAttack
15:10:58.001 [GravityGangAgentThread] ERROR org.openbase.planetsudo.game.GameSound --  ╚════⚀ Cannot invoke "java.net.URL.getFile()" because the return value of "java.lang.ClassLoader.getSystemResource(String)" is null
```
So in the old version it was failing. Please make sure you have tested the latest version, since it was one of the last code changes. And please Ignore the PlanetSudo AI Issues, those i will patch in the end. The development should focus on the engine.

2024-02-18 18:09 UTC, tommy33790 requested changes
- The call of `goTo` in `goToMothership()`, `goToSupportAgent()`, and `goToMarker` is similar but formatted differently.
- To keep in line with other `agent.is...` values I suggest turning `fun isShifting(): Boolean` into `val isShifting: Boolean`.
- Additionally the description of `fun shift()` in `AgentInterface` states "die nächsten 10 Schritte (agent.go...)" while the actual duration is difficult to calculate (3 times per go() a consumption of 0.01 unless collision is detected), which is why I'd prefer removing the specific number and writing something along the lines of "einige Schritte (agent.go...)".

If this is fixed I'm happy to approve the code

2024-02-18 18:30 UTC, tommy33790 commented on src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Agent.kt
> +            goTo {
Adding to my previous comment: this style in the brackets differs slightly from `goToSupportAgent` because there's no new line after `levelView`

2024-02-18 18:34 UTC, tommy33790 commented on src/main/kotlin/org/openbase/planetsudo/level/levelobjects/Agent.kt
> +            direction.apply {
Adding to my other comment: The syntax in `goTo{...}` differs from `goToSupportAgent` for example although having identical lines previously (disregarding `mothership` instead of `agentToSupport` and the `if(hasFuel())` of course)

2024-02-18 23:01 UTC, DivineThreepwood commented
Since the entire agent class was not well formatted and your mentioned style issues could be found at many spot I formatted the entire agent class. PR is ready to review again.

2024-02-19 11:26 UTC, DivineThreepwood commented
This PR should be prioritized since in contains lots of refactoring of the agent class.

2024-02-19 20:48 UTC, tommy33790 approved these changes
With the minor change for `hasTonic()` and `hasTonicForInvisibility()` requested (per new comment in `AgentInterface.kt`) the code is looking very good.

I tested it for the most part but another dedicated test by a fellow team member for these huge changes would be preferable.

2024-02-19 20:48 UTC, tommy33790 commented on src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentInterface.kt
> +    fun hasTonic(): Boolean = tonic >= 1
Minor detail: `hasTonic()` and `hasTonicForInvisibility()` slipped past the simplification of turning them into `val` as well

2024-02-19 20:55 UTC, DivineThreepwood commented on src/main/kotlin/org/openbase/planetsudo/level/levelobjects/AgentInterface.kt
> +    fun hasTonic(): Boolean = tonic >= 1
has both been addressed in the up-comming PR: #37

2024-02-19 21:07 UTC, merged